services:

  _defaults:
      public: true
      autowire: true
      autoconfigure: true

  gie_gateway.controller:
    class: Gie\GatewayBundle\Controller\GatewayController

  gie_gateway.command:
    class: Gie\GatewayBundle\Command\DeferredRequestsCommand
    tags:
      - { name: console.command }

  gie_gateway.request.manager:
    class: Gie\Gateway\Request\RequestManager

  gie_gateway.cache.manager:
    class: Gie\Gateway\Cache\CacheManager

  Gie\GatewayBundle\EventSubscriber\ResponseSubscriber: ~
