services:

  _defaults:
      public: true
      autowire: true
      autoconfigure: true

  gie_gateway.controller:
    class: Gie\GatewayBundle\Controller\GatewayController

  gie_gateway.command:
    class: Gie\GatewayBundle\Command\DeferredRequestsCommand
    tags:
      - { name: console.command }

  gie_gateway.request.manager:
    class: Gie\Gateway\Core\Request\RequestManager

  gie_gateway.cache.manager:
    class: Gie\Gateway\Core\Cache\CacheManager

  gie_gateway.request.subscriber:
    class: Gie\GatewayBundle\EventSubscriber\RequestSubscriber
    arguments:
      - '%gie_gateway.routes%'

  gie_gateway.response.subscriber:
    class: Gie\GatewayBundle\EventSubscriber\ResponseSubscriber
