services:

  _defaults:
      public: true
      autowire: true
      autoconfigure: true



  gie_gateway.controller:
    class: Gie\GatewayBundle\Controller\GatewayController

  gie_gateway.command:
    class: Gie\GatewayBundle\Command\DeferredRequestsCommand
    tags:
      - { name: console.command }

  Gie\Gateway\Core\Request\RequestManager: ~

  Gie\Gateway\Core\Cache\CacheManager: ~

  Gie\Gateway\API\Request\RequestManagerInterface: '@Gie\Gateway\Core\Request\RequestManager'
  Gie\Gateway\API\Cache\CacheManagerInterface: '@Gie\Gateway\Core\Cache\CacheManager'
  Gie\Gateway\API\Cache\Adapter\SetAdapterInterface: '@gie_gateway.cache.redis'


  gie_gateway.request.subscriber:
    class: Gie\GatewayBundle\EventSubscriber\RequestSubscriber
    arguments:
      - '%gie_gateway.routes%'

  gie_gateway.response.subscriber:
    class: Gie\GatewayBundle\EventSubscriber\ResponseSubscriber
